name: "Build iOS app"

on:
  # manual trigger but change to any supported event
  # see addl: https://www.andrewhoog.com/post/how-to-build-react-native-android-app-with-github-actions/#3-run-build-workflow
  workflow_dispatch:
    branches: [main]

jobs:
  build_with_signing:
    runs-on: macos-14
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.3

      - name: checkout repository
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Prepare Brew
        run: brew install boost openssl

      - name: Prepare LibTorrent
        run: ./Submodules/LibTorrent-Swift/make.sh

      - name: Install the Apple certificate and provisioning profile
        env:
          FIREBASE_INFO_PLIST_BASE64: ${{ secrets.FIREBASE_INFO_PLIST_BASE64 }}
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          BUILD_DISTRIB_CERTIFICATE_BASE64: ${{ secrets.BUILD_DISTRIB_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          BUILD_PROGRESS_WIDGET_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROGRESS_WIDGET_PROVISION_PROFILE_BASE64 }}
          BUILD_PROVISION_PROFILE_DISTRIB_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_DISTRIB_BASE64 }}
          BUILD_PROGRESS_WIDGET_PROVISION_PROFILE_DISTRIB_BASE64: ${{ secrets.BUILD_PROGRESS_WIDGET_PROVISION_PROFILE_DISTRIB_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          FIREBASE_INFO_PLIST_PATH=iTorrent/Core/Assets/GoogleService-Info.plist
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          CERTIFICATE_DISTRIB_PATH=$RUNNER_TEMP/build_distrib_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          PW_PP_PATH=$RUNNER_TEMP/build_progresswidget_pp.mobileprovision
          PP_DISTRIB_PATH=$RUNNER_TEMP/build_pp_distrib.mobileprovision
          PW_PP_DISTRIB_PATH=$RUNNER_TEMP/build_progresswidget_pp_distrib.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import firebase plist to the project
          echo -n "$FIREBASE_INFO_PLIST_BASE64" | base64 --decode -o $FIREBASE_INFO_PLIST_PATH

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_DISTRIB_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_DISTRIB_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
          echo -n "$BUILD_PROGRESS_WIDGET_PROVISION_PROFILE_BASE64" | base64 --decode -o $PW_PP_PATH
          echo -n "$BUILD_PROVISION_PROFILE_DISTRIB_BASE64" | base64 --decode -o $PP_DISTRIB_PATH
          echo -n "$BUILD_PROGRESS_WIDGET_PROVISION_PROFILE_DISTRIB_BASE64" | base64 --decode -o $PW_PP_DISTRIB_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security import $CERTIFICATE_DISTRIB_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles  
          cp $PW_PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles    
          cp $PP_DISTRIB_PATH ~/Library/MobileDevice/Provisioning\ Profiles  
          cp $PW_PP_DISTRIB_PATH ~/Library/MobileDevice/Provisioning\ Profiles        

      - name: build archive
        run: |
          xcodebuild \
          -workspace iTorrent.xcworkspace \
          -scheme "iTorrent" \
          -archivePath $RUNNER_TEMP/itorrent.xcarchive \
          -sdk iphoneos \
          -configuration Release \
          -destination generic/platform=iOS \
          clean archive          

      - name: export ipa
        env:
          EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
        run: |
          EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
          echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
          xcodebuild -exportArchive -archivePath $RUNNER_TEMP/itorrent.xcarchive -exportOptionsPlist $EXPORT_OPTS_PATH -exportPath $RUNNER_TEMP/build          

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repository: XITRIX/xitrix.github.io
          token: ${{ secrets.DISTRIB_REPO_ACCESS_TOKEN }}
          files: |
            ${{ runner.temp }}/build/iTorrent.ipa
            ${{ runner.temp }}/build/manifest.plist
        
      - name: Upload application
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ${{ runner.temp }}/build/iTorrent.ipa
          # you can also archive the entire directory 
          # path: ${{ runner.temp }}/build
          retention-days: 3
